# Generated by Django 2.2.5 on 2019-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='age',
            field=models.IntegerField(),
        ),
    ]
